spring:
  application:
    name: st-purchase-order
  datasource:
    driver-class-name: com.mongodb.Mongo
  data:
    mongodb:
      host: localhost
      port: 27017
      repositories:
        enabled: true
      database: po
      password: po
      username: po
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 6003
#  cloud:
#    config:
#      uri: http://localhost:5000

eureka:
  instance:
    hostname: 31.220.55.236
    port: 5002
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000 
    
destination:
  queue:
    email: email.box.q    
    nf: nf.generate.q
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.Query: DEBUG        
    